function n_state = tran_function(prev_state, controller_out, robot_params, time)
    % Input state has [pos_x, pos_y, theta, ...
    %                  controller_linear, controller_angular, ...
    %                  wheel_radius, wheel_separation, ...
    %                  start_time, end_time]
    % Input state size is [1, 10]
    
    wheel_r = robot_params(1);
    wheel_sep = robot_params(2);
    kinematicModel = differentialDriveKinematics("WheelRadius", wheel_r, ...
                                                 "TrackWidth", wheel_sep, ...
                                                 "VehicleInputs", ...
                                                 "VehicleSpeedHeadingRate");
    tspan = 0:time(2):time(2);

    [t, y] = ode45(@(t,y)derivative(kinematicModel, y, controller_out), tspan, prev_state);
    n_state = [y(end, 1); y(end, 2); y(end, 3)];
end