function n_state = tran_function(prev_state)
    % Input state has [now_pos_x, now_vel_x, new_vel_x, now_pos_y, ...
    %                  now_vel_y, new_vel_y, old_theta, old_omega, new_omega, ...
    %                  elapsed_time]
    % Input state size is [10, 1]

    new_theta = prev_state(8)*prev_state(end) + ... 
                0.5*(prev_state(9) - prev_state(8))*(prev_state(end)^2) +...
                + prev_state(7);
    
    state_x = [prev_state(1), prev_state(2), prev_state(3), new_theta, prev_state(end)];
    state_y = [prev_state(4), prev_state(5), prev_state(6), new_theta, prev_state(end)];

    n_state = [dynamics_const_acc(state_x, "x"); prev_state(2); prev_state(3); ...
               dynamics_const_acc(state_y, "y"); prev_state(5); prev_state(6); ...
               new_theta; prev_state(8); prev_state(9); prev_state(end)];
end